name: Update GAS(Google Apps Script)

on:
  push:
    paths:
      - src/**

  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest

    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ID_TOKEN: ${{ secrets.ID_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENTID }}
      CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
      SCRIPT_ID: ${{ secrets.SCRIPT_ID }}
      DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

    steps:
      - name: Setup repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Install Clasp
        run: npm ci
      - name: Generate ~/.clasprc.json
        run: bash deployment\setup.sh
      - name: Generate ~/.clasp.json
        run: bash deployment\setup_claspjson.sh
      - name: Push
        run: |
          cd src
          dir
          clasp push --force
      - name: Deploy
        run: |
          cd src
          dir
          clasp deploy --deploymentId ${{env.DEPLOYMENT_ID}}
