name: update GAS(Google Apps Script)

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: src

jobs:
  deploy:
    runs-on: windows-latest

    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      ID_TOKEN: ${{ secrets.ID_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENTID }}
      CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
      DEPLOYMENT_ID: ${{ secrets.DEPLOYMENT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: npm ci
      - run: bash deployment/setup.sh
      - run: bash deployment/setup_claspjson.sh
      - run: |
          cd src
          clasp push --forc
      - run: |
          cd src
          clasp deploy --deploymentId ${{env.DEPLOYMENT_ID}}
