# Sample workflow for building and deploying JSDoc site to GitHub Pages
name: Deploy refelence documents with GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    paths:
      - src/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    env:
      artifact: artifact.tar
      outputDir: out/
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: npm ci
      - name: JSDoc build
        run: npm run doc
      - name: Archive artifact
        shell: bash
        if: runner.os == 'Windows'
        run: |
          echo ::group::Archive artifact
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP\artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            --exclude=".[^/]*" \
            --force-local \
            "."
          echo ::endgroup::
        env:
          INPUT_PATH: ${{ env.outputDir }}
      - name: upload-artifact
        id: deployment
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ${{ runner.temp }}/${{ env.artifact }}
          if-no-files-found: error
      - run: rm ${{ env.artifact }}
        shell: "bash"
      - name: Setup Pages
        uses: actions/configure-pages@v5

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
